const state = {
  hotels: [],
  hotelDetails: [],
  adultCounts: [0, 1, 2, 3, 4, 5],
  childCounts: [0, 1, 2, 3, 4, 5],
  months: [
    "01",
    "02",
    "03",
    "04",
    "05",
    "06",
    "07",
    "08",
    "09",
    "10",
    "11",
    "12",
  ],
  years: [
    "2022",
    "2023",
    "2024",
    "2025",
    "2026",
    "2027",
    "2028",
    "2029",
    "2030",
    "2031",
    "2032",
    "2033",
  ],
  form_step: 1,
  datePickerLangSetting: {
    night: "Gece",
    nights: "Gece",
    "day-names": ["Pz", "Pzt", "Salı", "Çarş", "Perş", "Cuma", "Cts"],
    "check-in": "Giriş Tarihi",
    "check-out": "Çıkış Tarihi",
    "month-names": [
      "Ocak",
      "Şubat",
      "Mart",
      "Nisan",
      "Mayıs",
      "Haziran",
      "Temmuz",
      "Ağustos",
      "Eylül",
      "Ekim",
      "Kasım",
      "Aralık",
    ],
    tooltip: {
      minimumRequiredPeriod: "%{minNightInPeriod} %{night} minimum.",
    },
  },
  booking: {
    lastReservationId: "",
    selectedHotel: "",
    selectedHotelDetail: {},
    hotel_id: 0,
    start_date: "",
    end_date: "",
    adult: 0,
    child: 0,
    room_type: 0,
    room_scenic: 0,
    price: 0,
    coupon: {},
    couponCodeError: "",
    cc: {
      card_name: "",
      card_number: "",
      card_date_month: "",
      card_date_year: "",
      card_cvv: "",
    },
  },
};
export default state;
